// API surface to the Go backend. In production the Wails webview injects
// `window.go.main.App.<Method>` for every method bound in app.go; we call
// those directly. In a plain browser (vite dev without Wails) they're
// undefined, so we return mock values so the wizard UI is still navigable.
//
// Why not import from `wailsjs/go/main/App`? That path is generated by the
// Wails CLI and gitignored, so vite dev fails to resolve it for non-Wails
// contributors. Calling window.go directly keeps the dev path zero-config.

export type Status = {
  uv_installed: boolean;
  uv_version: string;
  ansible_core_installed: boolean;
  ansible_core_version: string;
  terraform_installed: boolean;
  terraform_version: string;
  bootstrap_message: string;
};

export type ValidationResult = { valid: boolean; errors: string[] };

declare global {
  interface Window {
    go?: { main?: { App?: Record<string, (...args: any[]) => Promise<any>> } };
  }
}

function call<T>(name: string, args: any[], mock: T): Promise<T> {
  const fn = window.go?.main?.App?.[name];
  if (fn) return fn(...args) as Promise<T>;
  console.warn(`[api stub] ${name} — Go backend not running, returning mock`);
  return Promise.resolve(mock);
}

export const api = {
  checkRuntime(): Promise<Status> {
    return call<Status>('CheckRuntime', [], {
      uv_installed: false,
      uv_version: '',
      ansible_core_installed: false,
      ansible_core_version: '',
      terraform_installed: false,
      terraform_version: '',
      bootstrap_message: '(dev) browser-only mode — Go backend not running',
    });
  },
  fetchContent(repo: string, ref: string): Promise<string> {
    return call<string>('FetchContent', [repo, ref], `(dev mock) ${ref}`);
  },
  validateInventory(yaml: string, dir: string): Promise<ValidationResult> {
    return call<ValidationResult>('ValidateInventory', [yaml, dir], { valid: true, errors: [] });
  },
  createRun(inv: unknown): Promise<string> {
    return call<string>('CreateRun', [inv], '(dev) mock-run-id');
  },
  planRun(id: string): Promise<string> {
    return call<string>('PlanRun', [id], '(dev) terraform plan would run here');
  },
  applyRun(id: string): Promise<void> {
    return call<void>('ApplyRun', [id], undefined);
  },
  resumeRun(id: string): Promise<unknown> {
    return call<unknown>('ResumeRun', [id], { id });
  },
  listRuns(): Promise<unknown[]> {
    return call<unknown[]>('ListRuns', [], []);
  },
};
