// API surface to the Go backend. In production the Wails webview injects
// `window.go.main.App.<Method>` for every method bound in app.go; we call
// those directly. In a plain browser (vite dev without Wails) they're
// undefined, so we return mock values so the wizard UI is still navigable.
//
// Why not import from `wailsjs/go/main/App`? That path is generated by the
// Wails CLI and gitignored, so vite dev fails to resolve it for non-Wails
// contributors. Calling window.go directly keeps the dev path zero-config.

export type Status = {
  uv_installed: boolean;
  uv_version: string;
  ansible_core_installed: boolean;
  ansible_core_version: string;
  terraform_installed: boolean;
  terraform_version: string;
  bootstrap_message: string;
};

export type ValidationResult = { valid: boolean; errors: string[] };

// VerifyCheck mirrors internal/state.VerifyCheck (run.json schema). One
// row per probe in the dev-vm verify stage; rendered in Step 6/7 as a
// PASS/FAIL checklist.
export type VerifyCheck = {
  id: string;        // ssh_os_release | hostname_ip_mac | network_dns | package_manager
  label: string;
  pass: boolean;
  detail?: string;
};

// Run is the lightweight subset Step 6/7 consumes from GetRun.
export type Run = {
  id: string;
  stage: string;
  last_error?: string;
  verify_results?: VerifyCheck[];
  inventory?: any;
};

// LeftoverISOs is the response from ListLeftoverISOs — what's still
// sitting under cluster-installer/ on the ISO datastore.
export type LeftoverFile = { name: string; size: number };
// owned=true → run-id matches one of OUR local runs (safe to wipe).
// owned=false → unknown owner (parallel installer? other tool?) — left alone.
export type LeftoverEntry = { path: string; owned: boolean; files: LeftoverFile[]; error?: string };
export type LeftoverISOs = {
  datastore: string;
  entries: LeftoverEntry[];
  total_gb: number;
  error?: string;
};

// Result of probing an ESXi host (or vCenter) and listing the resources
// the operator will pick from. Returned by App.DiscoverESXi(target).
export type ESXiDiscovery = {
  ok: boolean;
  error?: string;
  host?: {
    name: string;
    version: string;
    build: string;
    api_type: 'HostAgent' | 'VirtualCenter';
  };
  datastores?: Array<{
    name: string;
    type: string;          // VMFS / NFS / vSAN / …
    capacity_gb: number;
    free_gb: number;
    accessible: boolean;
  }>;
  networks?: Array<{
    name: string;
    vswitch?: string;
    vlan_id?: number;
  }>;
};

declare global {
  interface Window {
    go?: { main?: { App?: Record<string, (...args: any[]) => Promise<any>> } };
  }
}

function call<T>(name: string, args: any[], mock: T): Promise<T> {
  const fn = window.go?.main?.App?.[name];
  if (fn) return fn(...args) as Promise<T>;
  console.warn(`[api stub] ${name} — Go backend not running, returning mock`);
  return Promise.resolve(mock);
}

export const api = {
  checkRuntime(): Promise<Status> {
    return call<Status>('CheckRuntime', [], {
      uv_installed: false,
      uv_version: '',
      ansible_core_installed: false,
      ansible_core_version: '',
      terraform_installed: false,
      terraform_version: '',
      bootstrap_message: '(dev) browser-only mode — Go backend not running',
    });
  },
  fetchContent(repo: string, ref: string): Promise<string> {
    return call<string>('FetchContent', [repo, ref], `(dev mock) ${ref}`);
  },
  validateInventory(yaml: string, dir: string): Promise<ValidationResult> {
    return call<ValidationResult>('ValidateInventory', [yaml, dir], { valid: true, errors: [] });
  },
  createRun(inv: unknown): Promise<string> {
    return call<string>('CreateRun', [inv], '(dev) mock-run-id');
  },
  planRun(id: string): Promise<string> {
    return call<string>('PlanRun', [id], '(dev) terraform plan would run here');
  },
  applyRun(id: string): Promise<void> {
    return call<void>('ApplyRun', [id], undefined);
  },
  cancelRun(id: string): Promise<void> {
    return call<void>('CancelRun', [id], undefined);
  },
  resumeRun(id: string): Promise<unknown> {
    return call<unknown>('ResumeRun', [id], { id });
  },
  listRuns(): Promise<unknown[]> {
    return call<unknown[]>('ListRuns', [], []);
  },
  getRun(id: string): Promise<Run> {
    return call<Run>('GetRun', [id], { id, stage: 'pending' });
  },
  redeployDevVM(id: string): Promise<void> {
    return call<void>('RedeployDevVM', [id], undefined);
  },
  listLeftoverISOs(target: unknown): Promise<LeftoverISOs> {
    return call<LeftoverISOs>('ListLeftoverISOs', [target], { datastore: '', entries: [], total_gb: 0 });
  },
  wipeLeftoverISOs(target: unknown): Promise<void> {
    return call<void>('WipeLeftoverISOs', [target], undefined);
  },

  // Probe an ESXi/vCenter endpoint with the given target spec, return
  // the resources the operator should choose from (datastores, networks).
  // In dev/browser-only mode the stub returns realistic mock data so the
  // discovery → dropdown UX can be exercised without the Go backend.
  discoverEsxi(target: unknown): Promise<ESXiDiscovery> {
    // Mock matches the production IDC reference environment (Dell R760
    // with 6 SSD arrays in mixed sizes + a default datastore + 2 NFS
    // mounts + 1 inaccessible array for testing the filter). Real
    // govmomi probe replaces this in Phase 2.
    return call<ESXiDiscovery>('DiscoverESXi', [target], {
      ok: true,
      host: {
        name: 'esxi-r760-01.local',
        version: '8.0.2',
        build: '23299997',
        api_type: 'HostAgent'
      },
      datastores: [
        { name: 'datastore1',          type: 'VMFS', capacity_gb:  500, free_gb:  412, accessible: true },
        { name: 'SSD-RAID0-500Gi-01',  type: 'VMFS', capacity_gb:  500, free_gb:  468, accessible: true },
        { name: 'SSD-RAID0-500Gi-02',  type: 'VMFS', capacity_gb:  500, free_gb:  481, accessible: true },
        { name: 'SSD-RAID0-2Ti-01',    type: 'VMFS', capacity_gb: 2048, free_gb: 1530, accessible: true },
        { name: 'SSD-RAID0-2Ti-02',    type: 'VMFS', capacity_gb: 2048, free_gb: 1622, accessible: true },
        { name: 'SSD-RAID0-4Ti-01',    type: 'VMFS', capacity_gb: 4096, free_gb: 2891, accessible: true },
        { name: 'SSD-RAID0-4Ti-02',    type: 'VMFS', capacity_gb: 4096, free_gb: 2548, accessible: true },
        { name: 'NFS-iso',             type: 'NFS',  capacity_gb:  100, free_gb:   73, accessible: true },
        { name: 'NFS-backup',          type: 'NFS',  capacity_gb: 8192, free_gb: 6411, accessible: true },
        { name: 'OFFLINE-old-array',   type: 'VMFS', capacity_gb: 1024, free_gb:    0, accessible: false }
      ],
      networks: [
        { name: 'VM Network',                  vswitch: 'vSwitch0' },
        { name: 'Management Network',          vswitch: 'vSwitch0' },
        { name: 'Storage-Net (VLAN100)',       vswitch: 'vSwitch1', vlan_id: 100 },
        { name: 'Ceph-Cluster-Net (VLAN200)',  vswitch: 'vSwitch1', vlan_id: 200 },
        { name: 'DMZ',                         vswitch: 'vSwitch2', vlan_id: 50 }
      ]
    });
  }
};
