package imagecache

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"os"
	"path"
	"strings"

	"github.com/diskfs/go-diskfs"
	"github.com/diskfs/go-diskfs/disk"
	"github.com/diskfs/go-diskfs/filesystem"
	"github.com/diskfs/go-diskfs/filesystem/iso9660"
	"github.com/diskfs/go-diskfs/partition/mbr"
)

// RemasterAgamaISO produces a new bootable ISO at dstPath that is byte-
// for-byte identical to srcPath EXCEPT the bootloader configuration
// files (isolinux.cfg + grub.cfg) carry an extra kernel cmdline that
// points the installer at our HTTP-served auto-install profile. The
// result is what gets attached to a vSphere VM as its primary CD-ROM
// — direct kernel boot is unavailable on vSphere, so the only way to
// deliver an unattended Agama install is to bake the cmdline into the
// boot media itself.
//
// Layout assumptions (verified for openSUSE-Leap 16+ NET + Tumbleweed
// NET media):
//
//	El Torito boot file: /boot/x86_64/loader/isolinux.bin (BIOS), used by ESXi
//	BIOS firmware (the wizard ships firmware="bios" today).
//	Boot configs: /boot/x86_64/loader/isolinux.cfg + /EFI/BOOT/grub.cfg
//	+ /boot/grub2/grub.cfg.
//
// Both the Agama installer and the older AutoYaST installer accept their
// auto-install URLs via kernel cmdline:
//
//	Agama:    inst.auto=URL  (and inst.install_url=URL)
//	AutoYaST: autoyast=URL
//
// We inject all three so the same remaster works regardless of which
// installer the ISO ships. The unused params are simply ignored by the
// other installer.
func RemasterAgamaISO(ctx context.Context, srcPath, dstPath string, profileURL, installURL string, progress Progress) error {
	emit(progress, "%s  remastering → %s", path.Base(srcPath), path.Base(dstPath))

	srcInfo, err := os.Stat(srcPath)
	if err != nil {
		return err
	}

	src, err := diskfs.Open(srcPath, diskfs.WithOpenMode(diskfs.ReadOnly))
	if err != nil {
		return fmt.Errorf("open src iso: %w", err)
	}
	defer src.File.Close()

	srcFS, err := src.GetFilesystem(0)
	if err != nil {
		return fmt.Errorf("read src filesystem: %w", err)
	}

	// The new ISO will be approximately the source size. go-diskfs needs
	// a size hint at create-time; we add 64 MB margin for the rebuilt
	// directory tree + extra metadata blocks.
	dstSize := srcInfo.Size() + 64*1024*1024
	// Idempotent: clear leftover from a previously failed remaster.
	_ = os.Remove(dstPath)
	dst, err := diskfs.Create(dstPath, dstSize, diskfs.Raw, diskfs.SectorSizeDefault)
	if err != nil {
		return fmt.Errorf("create dst iso: %w", err)
	}
	defer dst.File.Close()
	dst.LogicalBlocksize = 2048

	dstFS, err := dst.CreateFilesystem(disk.FilesystemSpec{
		Partition:   0,
		FSType:      filesystem.TypeISO9660,
		VolumeLabel: "AGAMA-INST",
	})
	if err != nil {
		return fmt.Errorf("create dst fs: %w", err)
	}

	rewrite := func(rel string, data []byte) []byte {
		return rewriteBootCfg(rel, data, profileURL, installURL)
	}
	if err := copyTree(ctx, srcFS, dstFS, "/", rewrite, progress); err != nil {
		return err
	}

	isoFS, ok := dstFS.(*iso9660.FileSystem)
	if !ok {
		return fmt.Errorf("expected iso9660 filesystem, got %T", dstFS)
	}

	// El Torito boot record. openSUSE NET ISOs use isolinux.bin on the
	// BIOS side; ESXi VMs in this installer are configured firmware=bios
	// so this is the boot file we need. EFI booting (efi.img) is not
	// preserved by this remaster — the BIOS path is sufficient for v1.x.
	if err := isoFS.Finalize(iso9660.FinalizeOptions{
		RockRidge:        true,
		VolumeIdentifier: "AGAMA-INST",
		ElTorito: &iso9660.ElTorito{
			BootCatalog: "/boot.catalog",
			Platform:    iso9660.BIOS,
			Entries: []*iso9660.ElToritoEntry{
				{
					Platform:   iso9660.BIOS,
					Emulation:  iso9660.NoEmulation,
					BootFile:   "/boot/x86_64/loader/isolinux.bin",
					LoadSize:   4,
					BootTable:  true,
					SystemType: mbr.Linux,
				},
			},
		},
	}); err != nil {
		return fmt.Errorf("finalize iso: %w", err)
	}

	emit(progress, "%s  remaster done", path.Base(dstPath))
	return nil
}

// copyTree walks src recursively. Each regular file is streamed through
// to dst; directories are mkdir'd; the rewrite callback is given the
// chance to transform select files (here: bootloader configs).
//
// We special-case the El Torito boot catalog and isolinux.bin: both are
// regenerated by Finalize, so copying them from source would just be
// dead bytes. The boot catalog file ("boot.catalog" or "BOOT.CAT") is
// also created fresh by Finalize.
func copyTree(ctx context.Context, src, dst filesystem.FileSystem, dir string, rewrite func(string, []byte) []byte, progress Progress) error {
	entries, err := src.ReadDir(dir)
	if err != nil {
		return fmt.Errorf("readdir %s: %w", dir, err)
	}
	for _, e := range entries {
		if err := ctx.Err(); err != nil {
			return err
		}
		rel := path.Join(dir, e.Name())
		if e.IsDir() {
			if err := dst.Mkdir(rel); err != nil {
				return fmt.Errorf("mkdir %s: %w", rel, err)
			}
			if err := copyTree(ctx, src, dst, rel, rewrite, progress); err != nil {
				return err
			}
			continue
		}

		// Skip files Finalize will regenerate.
		if isElToritoBoilerplate(rel) {
			continue
		}

		if isBootCfg(rel) {
			if err := copyAndRewriteFile(src, dst, rel, rewrite); err != nil {
				return err
			}
			emit(progress, "  rewrote %s", rel)
			continue
		}

		if err := copyFileStream(src, dst, rel); err != nil {
			return fmt.Errorf("copy %s: %w", rel, err)
		}
	}
	return nil
}

func copyFileStream(src, dst filesystem.FileSystem, rel string) error {
	srcF, err := src.OpenFile(rel, os.O_RDONLY)
	if err != nil {
		return err
	}
	defer srcF.Close()

	dstF, err := dst.OpenFile(rel, os.O_CREATE|os.O_RDWR)
	if err != nil {
		return err
	}
	if _, err := io.Copy(dstF, srcF); err != nil {
		_ = dstF.Close()
		return err
	}
	return dstF.Close()
}

func copyAndRewriteFile(src, dst filesystem.FileSystem, rel string, rewrite func(string, []byte) []byte) error {
	srcF, err := src.OpenFile(rel, os.O_RDONLY)
	if err != nil {
		return err
	}
	data, err := io.ReadAll(srcF)
	_ = srcF.Close()
	if err != nil {
		return err
	}
	out := rewrite(rel, data)

	dstF, err := dst.OpenFile(rel, os.O_CREATE|os.O_RDWR)
	if err != nil {
		return err
	}
	if _, err := dstF.Write(out); err != nil {
		_ = dstF.Close()
		return err
	}
	return dstF.Close()
}

// isBootCfg picks the boot configs that own the kernel cmdline. We
// rewrite all variants (BIOS isolinux + UEFI grub2 + grub-rescue)
// because the same ISO can boot via any of them depending on firmware.
func isBootCfg(rel string) bool {
	base := strings.ToLower(path.Base(rel))
	return base == "isolinux.cfg" || base == "grub.cfg"
}

func isElToritoBoilerplate(rel string) bool {
	base := strings.ToUpper(path.Base(rel))
	return base == "BOOT.CAT" || base == "BOOT.CATALOG"
}

// rewriteBootCfg injects auto-install URL parameters into the kernel
// cmdline of every entry it can find. Conservative: never removes
// existing params, never reorders entries; just appends our four
// trailing tokens. The append is idempotent — re-running the remaster
// on an already-remastered ISO would simply duplicate the tokens but
// installers tolerate duplicate cmdline keys gracefully.
//
// Targets:
//   isolinux.cfg APPEND lines (case-insensitive, may have leading whitespace)
//   grub.cfg     "linux" or "linuxefi" lines inside menuentry blocks
func rewriteBootCfg(rel string, data []byte, profileURL, installURL string) []byte {
	suffix := fmt.Sprintf(" inst.auto=%s inst.install_url=%s autoyast=%s",
		profileURL, installURL, profileURL)

	lines := bytes.Split(data, []byte("\n"))
	for i, raw := range lines {
		trimmed := bytes.TrimLeft(raw, " \t")
		lower := bytes.ToLower(trimmed)
		switch {
		case bytes.HasPrefix(lower, []byte("append ")):
			// isolinux: APPEND ...
			lines[i] = bytes.TrimRight(raw, " \t")
			lines[i] = append(lines[i], []byte(suffix)...)
		case bytes.HasPrefix(lower, []byte("linux ")) || bytes.HasPrefix(lower, []byte("linuxefi ")):
			// grub2: linux /path/to/vmlinuz <args>
			lines[i] = bytes.TrimRight(raw, " \t")
			lines[i] = append(lines[i], []byte(suffix)...)
		}
	}
	return bytes.Join(lines, []byte("\n"))
}
